### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by heinrich5991** [django-denorm/django-denorm#29]
Is there a plan on supporting Python 3?

**Comment by PetrDlouhy** [comment]
I have collected all the compatibility patches from several branches and made django denorm to pass tests in Django versions 1.5 - 1.8 and Python versions 2.6/2.7/3.4.

Additional testing of the result on your project would be appreciated.

**Comment by PetrDlouhy** [comment]
This could be closed, since the test are passing under Python 3. If there is any problem with it, separate issue should be used.

**Comment by heinrich5991** [comment]
Sure, I'll close it. Thank you for your effort.
