### ISSUE TITLE
Incompatibility with Django 1.7 and migrations

### ISSUE THREAD

**Issue by puterleat** [django-denorm/django-denorm#36]
Now that django has migrations, it would be nice if django-denorm could play nicely.
At present, running manage.py migrate causes this error:

ImportError: Module "denorm.fields.DenormDBField" does not define a "DenormDBField" attribute/class

However, commenting out the decorator and property function while the migration runs solves the problem, so it seems it can't be that complex to fix. As a temporary workaround, wrapping the decorator and function in:

    if sys.argv[1] not in 'migrate makemigrations'.split():
        @denormalised
        def ...

solves the problem too.

**Comment by PetrDlouhy** [comment]
I have collected all the compatibility patches from several branches and made django denorm to pass tests in Django versions 1.5 - 1.8 and Python versions 2.6/2.7/3.4: https://github.com/whyflyru/django-denorm/pull/3

Additional testing of the result on your project would be appreciated.

**Comment by bashu** [comment]
closed via @f3f3d148ca89007ffe54023cd33c06608efa6e20
