### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by bashu** [django-denorm/django-denorm#47]
Hey,

Last release on pypi.python.org is dated 2013-09-24, is there a chance to see new minor / major release soon?

**Comment by PetrDlouhy** [comment]
This really should be done. The develop branch should be tested, merged with master and the PyPi package made.

**Comment by initcrash** [comment]
Unfortunately I have no idea who uploaded the version that is on PyPI right now, and I don't think one can just claim ownership of a package someone else uploaded.

**Comment by PetrDlouhy** [comment]
In PyPI written, that it is @WoLpH. Rick, could you please provide maintainers roles for @initcrash?

**Comment by WoLpH** [comment]
I've just tried, there is no user named @initcrash on Pypi. Any other maintainers I can add?

**Comment by WoLpH** [comment]
In the mean time, if there is a tested release available which I can push, feel free to let me know :)

Right now the setup.py still indicates 0.2.0 which would mean nothing changed as far as PyPI is concerned. If anyone can update those and tell me which branch to push to PyPI, I will :)

**Comment by bashu** [comment]
@WoLpH try to add @bashu

**Comment by initcrash** [comment]
@WoLpH my username on PyPI is "Christian.Schilling"

**Comment by WoLpH** [comment]
Done, both are added :)

**Comment by PetrDlouhy** [comment]
Hi, can we update the package now?

**Comment by hekevintran** [comment]
+1 Please do

**Comment by prokaktus** [comment]
Plus one for update version.

**Comment by PetrDlouhy** [comment]
There are two bugfixes to the develop branch in PRs, that should be pulled before releasing: #71 #66

@bashu, @initcrash - can we make the release after that? Or should I take over the project maintanence?

**Comment by PetrDlouhy** [comment]
I think, that Django denorm should make a new release and then drop support of old Django versions, make code cleaning and implement non-backward compatible changes in PR #28 

I would like to help with that, but I need much more flexibility with pulling my requests and making PyPI releases. @bashu, @initcrash can I get permissions to do that, please?

**Comment by hekevintran** [comment]
@bashu @initcrash Django denorm must be UNCHAINED!

**Comment by PetrDlouhy** [comment]
Hi, I have updated the code to currently supported Django versions in PR #85. The tests should be solid now. I think, that it is time to make new PyPI release after some basic testing.

**Comment by PetrDlouhy** [comment]
@bashu @initcrash @WoLpH This project hasn't been properly maintained for a long time. I have made several updates over past few years, but it is always taking very long time before they get to the main repository.

I would like to maintain this repository and PyPI packages. I would like to update the code to be compatible with current Django version and clean up the PRs and issues a bit.

Could you give me access permissions to the GitHub and PyPI, please?

**Comment by WoLpH** [comment]
For the time being I trhink that's the best solution indeed. Imho it should go through this repo but that's something out of my control, but I can help you with the Pypi rights :)

**Comment by bashu** [comment]
@PetrDlouhy go

**Comment by PetrDlouhy** [comment]
@bashu Many thanks. But I think, I have member permission to the `django-denorm` organisation, but no permissions to this repository (and I didn't find out how to gain them). Can you give me permissions to this repository?

**Comment by bashu** [comment]
@PetrDlouhy fixed
