### ISSUE TITLE
Release of django-denorm 1.0.0

### ISSUE THREAD

**Issue by PetrDlouhy** [django-denorm/django-denorm#86]
I have released package with version `1.0.0dev` on PyPI. It contains technological update to the currently supported Django versions and many other fixes and improvements.

I will make final `1.0.0` release shortly after this. If anyone is interested (@hekevintran, @prokaktus?), please test.

**Comment by prokaktus** [comment]
@PetrDlouhy hi! Unfortunately, I have no active projects, using Django-denorm. So I cannot provide any feedback 😞

**Comment by PetrDlouhy** [comment]
OK, I released the 1.0.0 version. It it has any problems, please report your issues.
